"""Stat group definitions (FBref-inspired) for feature selection subsets."""

# Each key is a group name; values are column names as they appear in the
# processed parquet files. Not all columns will exist for every position.
GROUPS = {
    "goalkeeping": [
        "SoTA",
        "GA",
        "Saves",
        "Save%",
        "CS",
        "PSxG",
        "PKatt",
        "PKA",
        "PKsv",
        "PKm",
        "Cmp",
        "Att",
        "Cmp%",
        "Att (GK)",
        "Thr",
        "Launch%",
        "AvgLen",
        "Opp",
        "Stp",
        "Stp%",
        "#OPA",
        "AvgDist",
    ],
    "passing": [
        "Cmp",
        "Att",
        "Cmp%",
        "TotDist",
        "PrgDist",
        "Ast",
        "xAG",
        "xA",
        "KP",
        "1/3",
        "PPA",
        "CrsPA",
        "PrgP",
    ],
    "pass_types": [
        "Live",
        "Dead",
        "FK",
        "TB",
        "Sw",
        "Crs",
        "TI",
        "CK",
        "In",
        "Out",
        "Str",
        "Cmp",
        "Off",
        "Blocks",
    ],
    "goal_shot_creation": [
        "SCA",
        "PassLive",
        "PassDead",
        "TO",
        "Sh",
        "Fld",
        "Def",
        "GCA",
    ],
    "defensive_actions": [
        "Tkl",
        "TklW",
        "Def 3rd",
        "Mid 3rd",
        "Att 3rd",
        "Att",
        "Tkl%",
        "Lost",
        "Blocks",
        "Sh",
        "Pass",
        "Int",
        "Tkl+Int",
        "Clr",
        "Err",
    ],
    "possession": [
        "Touches",
        "Def Pen",
        "Def 3rd",
        "Mid 3rd",
        "Att 3rd",
        "Att Pen",
        "Live",
        "Att",
        "Succ",
        "Succ%",
        "Tkld",
        "Tkld%",
        "Carries",
        "TotDist",
        "PrgDist",
        "PrgC",
        "1/3",
        "CPA",
        "Mis",
        "Dis",
        "Rec",
        "PrgR",
    ],
    "misc": [
        "CrdY",
        "CrdR",
        "2CrdY",
        "Fls",
        "Fld",
        "Off",
        "Crs",
        "Int",
        "TklW",
        "PKwon",
        "PKcon",
        "OG",
        "Recov",
        "Won",
        "Lost",
        "Won%",
    ],
    "performance": [
        "Gls",
        "Ast",
        "PK",
        "PKatt",
        "Sh",
        "SoT",
        "CrdY",
        "CrdR",
        "Touches",
        "Tkl",
        "Int",
        "Blocks",
        "xG",
        "npxG",
        "xAG",
        "SCA",
        "GCA",
        "Cmp",
        "Att",
        "Cmp%",
        "PrgP",
        "Carries",
        "PrgC",
        "Att",
        "Succ",
    ],
}
